### ISSUE TITLE
Calendar Filter use cases

### ISSUE THREAD

**Issue by mmarol** [risd/risd-undergraduate-welcome#10]
The audience options to choose from can change at a given time of the year. (Early-decision could be the only option at a certain point of the year, but at another point, early-decision, first-year and transfer can all be options to choose from.)
There are multiple use cases to account for:
  1. A user coming to a calendar style page for the first time.
    The user should only see the audience filter buttons (first-year, transfer etc). The buttons in this state should have styling that makes them larger. The calendar items should be hidden until an audience is selected. Once a button is clicked, the buttons should shrink and dates relevant to the audience selected should appear. The selection can change if another button is clicked.
  2. A user visiting a calendar style page, not for the first time, with the same audience options active. This could mean that the user is revisiting a calendar page, or that they have visited a calendar page before and are now visiting a different one.
    The user's last audience selection should be remembered by the browser and display the dates for that selection. This would mean the page appears the same as the end of Case 1.
  3. A user visiting a calendar style page, not for the first time, with different options active. This could mean that the user is revisiting a calendar page, or that they have visited a calendar page before and are now visiting a different one.
    If the last audience selected is still an active option, then run Case 2.
    If the last audience selected is now inactive, then run Case 1.
  4. A user visiting the site for the first time when there is only 1 audience option active.
    The user should not have to pick their audience in this case. The audience selection should happen automatically as there is only 1 audience option.

Case 1 and 2 are currently working, but Case 3 & 4 was not considered when this code was written. That might mean that all of this needs to be re-written.

**Comment by room421** [comment]
@rubillionaire Could you have a look at this issue early next week? You can reassign to Teddy if that makes more sense, but please let me know. Thanks!

**Comment by rubillionaire** [comment]
@room421 definitely. I've added it to my short list. I'll take a look and perhaps discuss with Teddy to see how we can get this addressed.

**Comment by rubillionaire** [comment]
@room421 I'll be able to take a look at this. I've got the code in place for tomorrows merge, and my list of items to work on is short, so I will take care of this.

@mmarol after poking at the code your write up makes good sense. I'll follow up with you if I have any questions.

**Comment by rubillionaire** [comment]
@mmarol The commit above captures my changes to this. I split the control flow of the script up a bit, and preserved most of the filtering functions.

Everything basically happens in the `audienceFilterGetSet` function, which does the job of getting the original audience string that is being filtered for to set the initial state. Whenever the audience filter value is set, the `onSetFn` is run on the value, all of the side effects of setting the value are run. These are captured in `onSetAudienceFilter`, which in turn does the local storage update, and runs the filter functions as you had them set.

I think I did the right thing with the day code, in the [initialization](https://github.com/risd/risd-undergraduate-welcome/blob/33af797fb1fafa3063925781900aa2dd57a5562f/script/src/calendarFilter.js#L49-L50), but it didn't look like I had a DOM that had those elements.

I pushed to develop, perhaps you can double check that things are working as you'd expect. If you have any sample pages that include cases that I had not considered yet, let me know and I can modify what I've got.

**Comment by mmarol** [comment]
@rubillionaire it's looking good. I checked all the cases I could think of so I think everything is covered. I will release into master and deploy 👍
