### ISSUE TITLE
Need input fields for page titles / meta descriptions & keywords

### ISSUE THREAD

**Issue by room421** [risd/risd-undergraduate-welcome#12]
Per the meeting this week, let's add fields to the congratulations.risd.edu CMS for editing page titles and meta description copy and/or other keywords. This copy should pass into the source HTML of a given page, e.g.:
```
<meta name="description" content="Lorem Ipsum Lorem Ipsum Lorem Ipsum. Lorem Ipsum Lorem Ipsum Lorem Ipsum.">
<meta name="keywords" content="Enrollment,Orientation">
```

It's ok if the page titles are assembled programmatically, but I'd like the ability to manually override it if so desired on a given page.

**Comment by mmarol** [comment]
Lauren's added the descriptions and a sitename and I've set up the templates to do implement them.

The meta description is unique for each page as search engines do not like it when descriptions on different pages are the same.

The meta title has the format of `_Page title_ | _Section title_ | Undergraduate Welcome | Rhode Island School of Design`. The Meta Title field in the CMS can override the `_Page title_ | _Section title_` part, but the ` | Undergraduate Welcome | Rhode Island School of Design` will always be constant. The `Undergraduate Welcome` text can be overwritten in the Settings part of the CMS.

**Comment by mmarol** [comment]
Keywords seem to be a deprecated SEO option. Search engines only look at title and description now from what I understand.

**Comment by mmarol** [comment]
@room421 if it looks good to you this issue can be closed.
