### ISSUE TITLE
Restructure CMS content types

### ISSUE THREAD

**Issue by teddybradford** [risd/risd-undergraduate-welcome#14]
The following steps need to be taken:

- [x] Duplicate `Important Dates` content type and entries into a new content type called `Universal - Post-Enrollment Info`
- [x] Delete all `Universal - Post-Enrollment Info` entries withOUT a "More Info" `Important Date Groups` relationship
- [x] Delete all `Important Dates` entries with a "More Info" `Important Date Groups` relationship _(This content type will later be renamed: `Universal - Calendar Items`)_
- [x] Duplicate `Programs` content type and entries into a new content type called `Universal - RISD Resources/Offices`
- [x] **Delete all `Universal - RISD Resources/Offices` entries with either an "Orientation programs" or "Exploring Providence" `Pages` relationship**
- [x] Duplicate `Programs` content type and entries into a new content type called `Universal - Providence General Info`
- [x] Delete all `Universal - Providence General Info` entries with either an "Inside RISD" or "Orientation programs" `Pages` relationship
- [x] Delete all `Programs` entries with either an "Inside RISD" or "Exploring Providence" `Pages` relationship _(This content type will later be renamed: `Universal - Orientation Programs`)_

- [x] Rename content types to reflect this reference sheet: https://docs.google.com/spreadsheets/d/1XWFbto13oySnT7YzT0SorkRdupclB2c9OJtA8MAL1Ao/edit#gid=346095834
- [x] Update templates to reflect content type changes

**Comment by teddybradford** [comment]
@cmiller02 When you get a chance, can you double check these steps to make sure they align with what we talked about?

**Comment by cmiller02** [comment]
Hi Teddy,

I reviewed your steps carefully and I think you almost had everything right. I think that only one step needed to be added, which I put in bold below. Other than that, the below steps are the steps you originally wrote out in this issue, except rearranged - my brain just did things in a different order when thinking it through - and I just added two notes in parentheses to keep my thoughts straight.

The following steps need to be taken:

- [ ] Duplicate `Important Dates` content type and entries into a new content type called `Universal - Post-Enrollment Info`
- [ ] Delete all `Universal - Post-Enrollment Info` entries withOUT a "More Info" `Important Date Groups` relationship
- [ ] Delete all `Important Dates` entries with a "More Info" `Important Date Groups` relationship _(This content type will later be renamed: `Universal - Calendar Items`)_
- [ ] Duplicate `Programs` content type and entries into a new content type called `Universal - RISD Resources/Offices`
- [ ] **Delete all `Universal - RISD Resources/Offices` entries with either an "Orientation programs" or "Exploring Providence" `Pages` relationship**
- [ ] Duplicate `Programs` content type and entries into a new content type called `Universal - Providence General Info`
- [ ] Delete all `Universal - Providence General Info` entries with either an "Inside RISD" or "Orientation programs" `Pages` relationship
- [ ] Delete all `Programs` entries with either an "Inside RISD" or "Exploring Providence" `Pages` relationship _(This content type will later be renamed: `Universal - Orientation Programs`)_


- [ ] Rename content types to reflect this reference sheet: https://docs.google.com/spreadsheets/d/1XWFbto13oySnT7YzT0SorkRdupclB2c9OJtA8MAL1Ao/edit#gid=346095834

**Comment by teddybradford** [comment]
@cmiller02 I was talking with Ruben and it appears that there isn't any tooling in place to do the duplication of existing content in this way. That brings us to 2 options:

1. I could make the new content types as prescribed, but they would be empty and require you to repopulate them with entries; or
2. Wait for the proper tooling to be created, which may take some time.

Which option would you like to go forward with?

**Comment by teddybradford** [comment]
I'm going to go ahead and see if I can duplicate at least some of the entries.

**Comment by teddybradford** [comment]
@cmiller02 I remembered you saying this was time sensitive, so I have renamed all the content types as per the spreadsheet.

The following content types need to be populated with entries:
* Universal - RISD Resources/Offices
* Universal - Providence General Info
* Universal - Post-Enrollment

**IMPORTANT** do NOT delete any entries from any content types yet; only add entries to these 3 new content types. Once they are added I will update the templates and at that point you can remove the duplicate entries from `Universal - Calendar Items` and `Universal - Orientation Programs`.

Let me know if you have any questions so far.

**Comment by cmiller02** [comment]
Thank you so much for doing this, @teddybradford ! I so appreciate you doing this last night, as I'll be spending most of the day adding to these entries - and your directions make complete sense. Thanks again!

**Comment by cmiller02** [comment]
Hi @teddybradford - just wanted to let you know that I copied all relevant items into:

Universal - RISD Resources/Offices
Universal - Providence General Info
Universal - Post-Enrollment

yesterday. So, whenever you're able to update the templates I'd really appreciate it. Thanks!

**Comment by teddybradford** [comment]
@cmiller02 I updated the templates to reflect the CMS changes. I also removed the duplicate entries from Orientation Programs. I'll let you remove the duplicate entries in Calendar Items.
