### ISSUE TITLE
Having "Upcoming Webinars" display as a header

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-undergraduate-welcome#15]
@teddybradford - can you please make it so the "Upcoming webinars" Calendar Item Group displays as a header the way "Open House Events," "More Info," and "Important Dates" do? (I believe this is controlled at the template level.)
![screen shot 2018-03-01 at 2 46 48 pm](https://user-images.githubusercontent.com/14020234/36866279-da69b572-1d5f-11e8-962b-d3eaeebf80e9.png)

When you do, can  you make it capital "U" and capital "W" for "Upcoming Webinars." 

My thinking is that once this is done "Upcoming Webinars" will display on this page above the "Early Decision Webinar":
![screen shot 2018-03-01 at 2 51 13 pm](https://user-images.githubusercontent.com/14020234/36866360-12032c52-1d60-11e8-9699-0673f0f00fd2.png)

the way "Open House Events" does on this page:
![screen shot 2018-03-01 at 2 53 21 pm](https://user-images.githubusercontent.com/14020234/36866457-51ebe016-1d60-11e8-9ded-1f79d28a0869.png)

Thanks so much!

**Comment by teddybradford** [comment]
@cmiller02 I removed a style that was blocking the Upcoming Webinars title from displaying. Lemme know if it looks right to you now.

**Comment by cmiller02** [comment]
It's perfect, @teddybradford - thank you! I'll close this issue now.
