### ISSUE TITLE
Standardizing new content type names across the CMS fields

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-undergraduate-welcome#16]
Hi @teddybradford:

I made a list of all the instances that I could find of fields that are titled with the older content type names that I would really love to get changed to match the new content type names. My apologies for the length of this, but it seemed to make more sense to keep these items together. Thanks SO much, and please just let me know if anything is unclear:

1. In Universal - Calendar Items, can you please change the names of these two fields: "Pages (Important Dates)" to "Universal - Pages" and "Date Group" to "Universal - Calendar Item Group":
![screen shot 2018-03-02 at 11 03 38 am](https://user-images.githubusercontent.com/14020234/36908656-daf11954-1e09-11e8-9bf3-2034a2317243.png)

2. In Universal - Orientation Program items, can you please change the name of the field "Pages(Programs)" to "Universal - Pages"
![screen shot 2018-03-02 at 11 14 35 am](https://user-images.githubusercontent.com/14020234/36909109-26309c9a-1e0b-11e8-8b49-5741fb35587b.png)

3. In Universal - Post-Enrollment Info items, can you please delete the "Pages(Important Dates)" field, since we have the "Universal - Pages" field
![screen shot 2018-03-02 at 11 23 18 am](https://user-images.githubusercontent.com/14020234/36909658-9bba46d6-1e0c-11e8-9042-831d2e7ead5e.png)

4. In Universal - Providence General Info items, can you please delete the "Pages(Programs)" field, since we have the "Universal - Pages" field
![screen shot 2018-03-02 at 11 31 01 am](https://user-images.githubusercontent.com/14020234/36909938-605873a0-1e0d-11e8-95cb-f7c6f812c8f5.png)

5. In Universal - Providence Specifics items, can you please change the name of the field "Pages(Transportation" to "Universal - Pages"
![screen shot 2018-03-02 at 11 33 43 am](https://user-images.githubusercontent.com/14020234/36910132-d84861ea-1e0d-11e8-8035-ef2f99ecfec9.png)

6. In Universal - RISD Resources/Offices items, can you please delete the "Pages(Programs)" field, since we have the "Universal - Pages" field
![screen shot 2018-03-02 at 11 37 26 am](https://user-images.githubusercontent.com/14020234/36910324-5f67e0f6-1e0e-11e8-81b9-52c072925608.png)

7. In Universal - Stories, can you please change the name of the field "Pages" to "Universal - Pages"
![screen shot 2018-03-02 at 11 40 10 am](https://user-images.githubusercontent.com/14020234/36910390-9c40b23c-1e0e-11e8-9208-3d56a6cf4afb.png)

8. For Phase 1 - Secondary Nav items and Phase 2 - Secondary Nav items, can we just have the following fields:

"Name"
"Universal - Pages"
"Phase 1 Navigation"
"Phase 2 Navigation"

and with the "Phase 1 Navigation" field can we say something like "type "Main Nav" in this field for this page(s) to display in this section of the Phase 1 Navigation"
and with the "Phase 2 Navigation" field can we say something like "type "Main Nav" in this field for this page(s) to display in this section of the Phase 2 Navigation"

9. A little backstory: Right now I need Universal - Post-Enrollment Info items to still have the "Date Group" field - because I have three of these items still sitting on http://congratulations.risd.edu/next-steps/next-steps-to-enroll under the "More Info" header. Soon, though, we will have a page with additional (non date-based general planning info for students) that I'm working on here: https://risd-undergraduate-welcome.risd.systems/_wh_previews/pages/e0da5ab9-d75c-ccd8-9179-2bad8880f218/ and once this is live I will take the "More Info" items off of this page: http://congratulations.risd.edu/next-steps/next-steps-to-enroll/ and we'll be able to remove the "Date Group" field from the Universal -
 Post-Enrollment Info items (since Post-Enrollment items aren't date based). Given these future events, can we possibly add a field for Universal - Post-Enrollment items that will allow for them to fall under a given header?  Right now, on https://risd-undergraduate-welcome.risd.systems/_wh_previews/pages/e0da5ab9-d75c-ccd8-9179-2bad8880f218/ the items fall under the "More Info" header (because I have the 3 "More Info" items on that page - that are also on http://congratulations.risd.edu/next-steps/next-steps-to-enroll/ but I'll be taking those three items off of the next steps to enroll page and it would be great to be able to choose a header for all the items on https://risd-undergraduate-welcome.risd.systems/_wh_previews/pages/e0da5ab9-d75c-ccd8-9179-2bad8880f218/ And when we do take those 3 items off of the next steps to enroll page we can then also delete "More Info" as a Universal - Calendar Item Group. Phew! hope that wasn't too confusing, but please just let me know if it was. So I guess the first step here would be enabling a header to be added to Universal - Post-Enrollment Info items.

10. For Universal - Pages items, can you take the following fields and change their names:

- "Stories" to "Universal - Stories"
- "Programs" to "Universal - Orientation Programs"  
- "RISD Resources/Offices" to "Universal - RISD Resources/Offices"
- "Providence General Info" to "Universal - Providence General Info"
- "Resources" to "Universal - Images Gallery"
- "Alumni Bios" to "Universal - Alumni Bios"
- "Lists" to "Universal - Graphic Alumni Lists"
- "Important Dates" to "Universal - Calendar Items" 
- "Information Snippets" to "Universal - Providence Specifics"
- "Post-Enrollment Info" to "Universal - Post-Enrollment Info"

and these three, which are at the very bottom of the page, can be deleted 
- Universal - Post-Enrollment Info (Pages (Important Dates))
- Universal - RISD Resources/Offices (Pages (Programs))
- Universal - Providence General Info (Pages (Programs))

THANK YOU SO SO MUCH!

**Comment by teddybradford** [comment]
@cmiller02 I've tackled 1-8, and 10. There were a few tricky things that had to happen due to limitations of Webhook CMS, but I think I was able to get everything working properly with the updated naming scheme.

We should revisit 9 next week. I'm a little unclear as to what exactly you want, so we can go over that together.

**Comment by cmiller02** [comment]
Hey @teddybradford - sorry for the confusion on #9.

Let me see if I can make this clearer with some images:

So right now we have this page: http://congratulations.risd.edu/next-steps/next-steps-to-enroll/#early-decision which looks like this:
![screen shot 2018-03-06 at 8 56 26 am](https://user-images.githubusercontent.com/14020234/37036012-64b6365a-211c-11e8-92ef-583a988a1679.png)

We want to change this page to take the More Info stuff at the bottom off of it. I have already put these items on another page, that I just haven't published yet and that looks like this:

![screen shot 2018-03-06 at 8 59 20 am](https://user-images.githubusercontent.com/14020234/37036126-b49b50b0-211c-11e8-9bfb-0c50e95a1ce2.png)

Before I publish this page, though, I'm wondering if you can do two things for me:
1. (per my other Github issue) can you please make it so the audience filter can work for [this page](https://risd-undergraduate-welcome.risd.systems/cms/#/wh/content/universalpages/-L6bPXa0LyP6tzxDIDh1):
![screen shot 2018-03-06 at 9 09 42 am](https://user-images.githubusercontent.com/14020234/37036609-2e5cb51e-211e-11e8-9e39-da9797a059d7.png) (more info in the other Github issue)
2. This page is made up of Universal - Post-Enrollment Info items, and the "Date Group" field:
![screen shot 2018-03-06 at 9 12 43 am](https://user-images.githubusercontent.com/14020234/37036759-962ffd40-211e-11e8-9f4b-e1c5a51ed4b7.png) for these items doesn't make sense anymore. (If you recall we pulled the Universal - Post-Enrollment Info items out from being within Calendar Items, so for them to still have the "Date Group" field (which stems from the Universal Calendar Item Groups) doesn't make sense (basically Universal - Post-Enrollment Info items are NOT date based). So, I'm wondering if you can remove the "Date Group" field from Universal - Post-Enrollment Items. But, once you do that, I'll still need a way to make a header appear on this page: 
![screen shot 2018-03-06 at 9 19 15 am](https://user-images.githubusercontent.com/14020234/37037059-7cc9644e-211f-11e8-86e1-7e4ac07205a8.png) (We'll want to just have the text read something other than More Info at the top) So, I'm wondering if you can create a field that enables a header so that we can make whatever text we want, instead of More Info, appear at the top. Does this make sense?

Also, was wondering if you could look back to 1. in my first comment - I put the second part of the request in bold. (Not sure if you saw that that one had two parts to it).

THANKS SO SO MUCH FOR ALL THESE DETAILS and if you want to talk over the phone at some point, if this still is too crazy to follow, please just let me know.

**Comment by teddybradford** [comment]
@cmiller02 Thanks for clarifying that. I've gone ahead and updated the systems site. I've enabled the audience filter for post-enrollment info as per #17. There's also now a field in the pages content type that let's you specify a post-enrollment info title. If no title is entered there, it will default to "More Info" on the page.

> Also, was wondering if you could look back to 1. in my first comment - I put the second part of the request in bold. (Not sure if you saw that that one had two parts to it).

The first item you listed in this issue? I don't see any bold text. Can you copy+paste the bit that I missed?

**Comment by cmiller02** [comment]
Hey @teddybradford - I just got out of a meeting and am so excited about all the progress you've made! Thank you! Sorry, I must have forgotten to save the bold. Here's what I think you might have missed:

In Universal - Calendar Items, can you please change the name of the field called "Date Group" to instead be "Universal - Calendar Item Group"

The audience filter and header look great!

**Comment by teddybradford** [comment]
Finished! 🏁
