### ISSUE TITLE
Change to Audience Filters setting

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-undergraduate-welcome#17]
Hi @teddybradford 

in Universal - Pages entries, can you make it so that my selection of Audience Filters:Show affects "Universal - Calendar Items" and "Universal - Post-Enrollment Info" items. Right now "this only affects pages with Important Dates." Thank you!

![screen shot 2018-03-02 at 1 07 14 pm](https://user-images.githubusercontent.com/14020234/36914434-4a86d928-1e1b-11e8-9fe1-e3ead98ae243.png)

**Comment by teddybradford** [comment]
@cmiller02 Can you explain what the Audience Filter setting does and how it affects a page when enabled currently?

**Comment by cmiller02** [comment]
Of course! So right now we have all audiences turned off, except for the Early Decision audience. So, if you take a look at this page: 
![screen shot 2018-03-06 at 1 35 30 pm](https://user-images.githubusercontent.com/14020234/37051013-657461a8-2143-11e8-8b34-43a581314971.png)
Do you see how there is a button towards the top that says "Early Decision?" Since the Early Decision audience type is currently the only one turned on, that is the only button that appears there and the 3 dates under the Important Dates header are there because they belong to the "Early Decision" audience type. When we turn the other 3 audience types on: First-Year, Transfer, and Brown|RISD Dual Degree, there will be 3 more buttons there and when you click on them appropriate Important Dates will appear. I think that Jay set the Audience Filter to only work in relation to pages that have Important Dates on them (now called Universal - Calendar Items) but now Universal - Post-Enrollment Info items are in their own content type, so they aren't affected by the filter now. Does this help?

**Comment by teddybradford** [comment]
I've enabled the audience filter for post-enrollment info!

**Comment by cmiller02** [comment]
woohoo! This looks great!
![screen shot 2018-03-06 at 4 49 55 pm](https://user-images.githubusercontent.com/14020234/37060495-7a016010-215e-11e8-87ab-659af5c7f893.png)

**Comment by teddybradford** [comment]
Hooray! 🎉
