### ISSUE TITLE
Rearranging menu in Phase 2 of site

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-undergraduate-welcome#18]
Hey @teddybradford, I have an additional top nav section that I've created, called MOVING HERE, that houses 4 pages. I haven't actually added it to the top navigation yet, though, because that will mean moving from having 4 nav sections to 5, an odd number.  So I'm wondering if (by March 21st) you can please move the (now central) RISD logo in the nav to the far left, so it would look like this:

![unnamed](https://user-images.githubusercontent.com/14020234/37213131-1f34b5ba-237f-11e8-9d1f-19e798f42eb0.png)

Jay tells me that, right now, the RISD logo is positioned to fall after the second nav item, so he says that you'd just need to specify that it (instead) fall before the first nav item (NEXT STEPS). 

So, if you could please change this at the template level I'd really appreciate it.

Oh, but I am waiting on confirmation of text on one of the 4 pages in this section, so do you mind letting me know before you deploy this?

Thanks so much, and please just let me know if you have any questions,
Carrie

**Comment by teddybradford** [comment]
Done!

**Comment by cmiller02** [comment]
All is great, @teddybradford ! Thank you so much! I'm going to close this out.
