### ISSUE TITLE
Adding Title Field for Universal - Calendar Items

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-undergraduate-welcome#19]
Hi @teddybradford -

So I just added the dates from the [Online events page](https://congratulations.risd.edu/next-steps/online-events/#early-decision) to the [Enrollment and beyond page](https://congratulations.risd.edu/next-steps/enrollment-and-beyond/#early-decision). 

I also just added the dates from the [Join us for an Open House page](https://congratulations.risd.edu/next-steps/join-us-for-an-open-house/#early-decision) to that same page ([Enrollment and beyond](https://congratulations.risd.edu/next-steps/enrollment-and-beyond/#early-decision)).

Doing this required me to change the items in Upcoming webinars and Open house events:
![screen shot 2018-03-15 at 3 10 05 pm](https://user-images.githubusercontent.com/14020234/37485857-0cb92f86-2863-11e8-9411-9bffb2e601c9.png)

to have this setting:
![screen shot 2018-03-15 at 3 08 32 pm](https://user-images.githubusercontent.com/14020234/37485866-12f045e2-2863-11e8-8b35-e429e9927d50.png)

So that all dates on [Enrollment and beyond](https://congratulations.risd.edu/next-steps/enrollment-and-beyond/#early-decision) fall under one header - "Important dates." 

So, consequently, now the [Online events page](https://congratulations.risd.edu/next-steps/online-events/#early-decision) and the [Join us for an Open House page](https://congratulations.risd.edu/next-steps/join-us-for-an-open-house/#early-decision) no longer have their unique headers and now also say "Important dates" across the top. To remedy this, can you add (on Universal - Pages) a title field that can be applied to Universal - Calendar Items, like you did here for Universal - Post-Enrollment Info items:

![screen shot 2018-03-15 at 3 21 15 pm](https://user-images.githubusercontent.com/14020234/37486322-8a1300b4-2864-11e8-93dd-8220c33a829b.png)

Thanks! And after this is done I don't think we need the "Universal - Calendar Item Groups" content type - since 3 out of the 4 groups aren't being used. (But we can talk about that later if that's easier.) Please just let me know if you have any questions.

**Comment by teddybradford** [comment]
@cmiller02 I added the calendar items title field to pages and updated the templates for the risd.systems site. Once you verify that this new feature is working properly, I'll push the change to the production site. fdb781c0bf9d10cf766de308bf0f9d87d6effe81

**Comment by cmiller02** [comment]
Things are working perfectly on the systems site, @teddybradford ! Thank you! Here are the two pages I used the field on: 

https://risd-undergraduate-welcome.risd.systems/next-steps/join-us-for-an-open-house/#early-decision and 
https://risd-undergraduate-welcome.risd.systems/next-steps/online-events/#early-decision. 

Whenever you can push this change that would be great!

**Comment by teddybradford** [comment]
Pushed to production site!
