### ISSUE TITLE
Footer no longer has sitemap

### ISSUE THREAD

**Issue by mmarol** [risd/risd-undergraduate-welcome#21]
The current footer is missing some content. I think the content type name changes didn't get applied to the footer.

Current footer:
<img width="1424" alt="screen shot 2018-03-20 at 11 32 49 am" src="https://user-images.githubusercontent.com/6997772/37664884-7844c936-2c32-11e8-8f91-4c1928e99cf5.png">

Old footer:
<img width="1423" alt="screen shot 2018-03-20 at 11 34 29 am" src="https://user-images.githubusercontent.com/6997772/37665006-b72814d2-2c32-11e8-92f7-e96b93633ed9.png">

**Comment by teddybradford** [comment]
Fixed a28967724b9de9846d7c68290e04eb3e0c3a10de
