### ISSUE TITLE
Making "Universal - Orientation Programs" come before "Universal - Calendar Items" on "Universal - Pages"

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-undergraduate-welcome#25]
@teddybradford - we're going to have a few pages on the site look like this: https://risd-undergraduate-welcome.risd.systems/_wh_previews/universalpages/ddd79678-6979-2f81-9a91-2e839e90e640/ HOWEVER, we'd like for the image with text element: 
![screen shot 2018-05-22 at 1 01 33 pm](https://user-images.githubusercontent.com/14020234/40377996-4c790d34-5dc0-11e8-8420-c171061048d0.png)

to come before the header with dates element:
![screen shot 2018-05-22 at 1 04 44 pm](https://user-images.githubusercontent.com/14020234/40378184-c77b7af8-5dc0-11e8-85f5-b4e026c12e9d.png)

So, in order to do this, can you make "Universal - Orientation Programs" come before "Universal - Calendar Item" when they are both used on a "Universal - Pages"

Another example of a page that will be changed the same way, after this reordering will be: https://risd-undergraduate-welcome.risd.systems/_wh_previews/universalpages/d7ba5b01-8a68-8ea6-bd16-8e977036298e/

Here are the fields on the POSE page (we also use an image gallery here, but that falling at the bottom of the page is already good)
![screen shot 2018-05-22 at 1 07 20 pm](https://user-images.githubusercontent.com/14020234/40378312-2ebfca70-5dc1-11e8-8e12-ae9ce4722eb7.png)

Thanks so much, and please just let me know if you have any questions at all. I'm back in tomorrow at 8:30. - Carrie

**Comment by teddybradford** [comment]
Completed! 🙂

**Comment by cmiller02** [comment]
All looks great - thanks @teddybradford ! Going to close this one out.
