### ISSUE TITLE
10 broken links resulting from favicons

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-undergraduate-welcome#7]
Hey Jay,

I got this from Siteimprove:

![screen shot 2017-04-24 at 12 29 24 pm](https://cloud.githubusercontent.com/assets/14020234/25347864/4e1443fe-28ea-11e7-8b88-6814329aec5b.png)

I think that Brian mentioned either this same or a similar issue on the grad site - and I don't know if you fixed things there yet, but anyway, just let me know if you need any more info on this.

Thanks,
Carrie

**Comment by cmiller02** [comment]
@teddybradford took care of this - no longer showing up in Siteimprove results. Closing this issue now.

**Comment by cmiller02** [comment]
@teddybradford - I think this issue has reared its head again. I just initiated a recrawl on Siteimprove, just to be sure, but when I went into Siteimprove today this same thing with the favicons seemed to be happening:

![screen shot 2018-03-15 at 5 25 52 pm](https://user-images.githubusercontent.com/14020234/37492004-02d31212-2876-11e8-90e2-26a85f3c1555.png)

**Comment by teddybradford** [comment]
I just put a change in that should fix this: 2f65a18ac4bf5d710a3a9842087dc5579440c48b

**Comment by cmiller02** [comment]
Thanks so much for this, @teddybradford - it did indeed fix these Siteimprove results. So, I'm going to close this out.
